### ISSUE TITLE
Maintainance plans

### ISSUE THREAD

**Issue by HugoP707** [mrDIMAS/DmitrysEngine#3]
Hello, I was wondering if the project is still being maintained or if it has been abandoned.
Thanks in advance.

**Comment by mrDIMAS** [comment]
Hi! Project is abandoned, I've completely switched to Rust from C, fully ported [the engine to Rust](https://github.com/mrDIMAS/rg3d) and it is in active development.

**Comment by HugoP707** [comment]
ok, thats a bit sad bc i really needed a c api, but thanks for your reply
